base:
  seed: 42
model:
  type: Llama
  path: meta-llama/Llama-3.2-3B
  tokenizer_mode: slow
  torch_dtype: auto
calib:
  name: pileval
  download: true
  n_samples: 128
  bs: -1
  seq_len: 2048
  preproc: pileval_awq
  seed: 42
eval:
  eval_pos:
  - fake_quant
  name: wikitext2
  download: true
  seq_len: 2048
  bs: 1
  inference_per_block: false
quant:
  method: Awq
  weight:
    bit: 4
    symmetric: true
    granularity: per_group
    group_size: 128
  special:
    trans: true
    trans_version: v2
    weight_clip: true
    clip_sym: true
save:
  save_trans: false
  save_fake: true
  save_vllm: false
  save_path: /mnt/e/seq v4/SEQ-clean-v4/runs/final/llmc/Llama-3.2-3B/awq/artifacts
